### ISSUE TITLE
Add support for BungeeCord?

### ISSUE THREAD

**Issue by SystemUpdate** [SquidHQ/plugin#1]
So we can install the plugin on our proxy

**Comment by AlfieC** [comment]
Why is this required? The goal of SquidHQ is to remove Mojang's blocklist. I don't see any need for this to be BungeeCord based. What about servers with more than one BungeeCord instance? 

You could just write your own BungeeCord plugin using the nicely provided plugin messaging system. I'll provide an example from the Spigot wiki below.

```  
  ByteArrayDataOutput out = ByteStreams.newDataOutput();
  out.writeUTF("Subchannel");
  out.writeUTF("Argument");

  // If you don't care about the player
  // Player player = Iterables.getFirst(Bukkit.getOnlinePlayers(), null);
  // Else, specify them
  Player player = Bukkit.getPlayerExact("Example");

  player.sendPluginMessage(this, "BungeeCord", out.toByteArray());
  ```

Unless I'm missing something here, I really see no reason at all for the plugin being on a BungeeCord but I'm of course open for any reasons I can't think of.

**Comment by YoloxPanda** [comment]
I love when people request for things as an issue :)

**Comment by coelho** [comment]
@YoloxPanda It's not like we have any other place right now to request things :p This is fine.

**Comment by DeadZombieGrow** [comment]
problem is this plugin dont work for bungeecord servers. I tried placing it on the server and it didnt work.

**Comment by DeadZombieGrow** [comment]
coelho pls help

**Comment by Yive** [comment]
![bungeecord](https://i.tcpr.ca/y59bORX)

Bungeecord works perfectly here.

**Comment by DeadZombieGrow** [comment]
Do i need to drop the plugin in both bungeecord and spigot server?

**Comment by Yive** [comment]
Just the spigot server. Make sure your bungeecord is not from before August 26, 2016

**Comment by coelho** [comment]
This issue is resolved in the latest Bungeecord version. Simply install the plugin on your Spigot server.
