### ISSUE TITLE
Coding Conventions, OOP?

### ISSUE THREAD

**Issue by j0ach1mmall3** [SquidHQ/plugin#5]
Would it be possible to change the variable at https://github.com/SquidHQ/plugin/blob/master/src/com/squidhq/plugin/APISingleton.java#L5 to not include an underscore prefix?
Also, I don't see the purpose of creating and implementing an API, when the only use is this plugin. Do you guys plan on having seperate API implementations, and if so, shouldn't the API be in a seperate repository. If not, I think it would be easier to not use static and just let the API users invoke JavaPlugin#getPlugin to get the Main/API instance

**Comment by coelho** [comment]
The API interface is to keep implementation details outside of the API.
The "_api" is to signify that you should use the appropriate accessor method.
No, we're not using JavaPlugin.getPlugin. Static accessors are a million times easier from an API standpoint.
